### ISSUE TITLE
Add option to disable adding a subpage form on the attachment page

### ISSUE THREAD

**Issue by andrewdbate** [Gittenburg/Attachments#6]
Would it be possible to add a configuration option to disable displaying the "add subpage" form on the "attaching to" page?

On our wiki subpages are uncommon, so being given the option to add a subpage each time a user wants to add a file attachment is confusing (for our usage at least), particularly since it is the first form on the page.

For completeness, it would also be useful to add an option to disable the "add link" form. That way, the attachments extension could be configured just for file attachments only by disabling both the "add subpage" and the "add link" form.

Many thanks again!

**Comment by Gittenburg** [comment]
My reason for placing the subpage form prominently as the first option was to encourage users to create subpages as opposed to uploading files, since wiki pages are way better for collaborative editing (can be edited directly in the browser, edit diffs can be viewed in the history tab), while file uploads need to be downloaded, edited and uploaded again and don't provide meaningful edit diffs. And collaborative editing is pretty much what a wiki is about. MediaWiki by default doesn't provide any discoverable user interface to create subpages, so maybe your wiki just doesn't have many subpages since your users are unaware of them?

That said, I can see the "Add subpage" form being confusing for users less familiar with MediaWiki and I get the appeal of streamlining a user interface for your most common use case. I however also don't want to succumb to feature creep, offering many configuration settings only very few people will care for.

The best option seems to be wrapping the forms in divs with CSS classes, allowing you to hide them by adding `display: none` rules to your `MediaWiki:Common.css`. Would that address your concern?

**Comment by andrewdbate** [comment]
It's understandable that you probably want to avoid adding many configuration settings. I also agree that users should be creating pages on the wiki over attachments whenever possible. Our use of attachments is mostly for PDFs of papers, or small example data sets, etc.

However, wrapping the form in a div as hiding it with CSS seems more hacky than adding a config option. It would also be more difficult to configure and maintain the extension because the configuration options would not be all set in one place (some in CSS and some in `LocalSettings.php`).

**Comment by Gittenburg** [comment]
Fair enough. Resolved by aa8ac0181d0b2915494db7ea469ab1fff960fe60.
