### ISSUE TITLE
Document configuration parameters in the README

### ISSUE THREAD

**Issue by andrewdbate** [Gittenburg/Attachments#7]
Do you think that `$wgAttachmentsChunkListByLetter` should be mentioned in `README.md`?

Perhaps it should say something like:
_By default, attachments will be grouped by first digit or letter into separate lists. To turn this off, so that attachments are displayed in a single list, add `$wgAttachmentsChunkListByLetter = false;` to your `LocalSettings.php` file._

What do you think?

Many thanks again!

**Comment by Gittenburg** [comment]
I previously just documented them in the [mediawiki.org wiki page](https://www.mediawiki.org/wiki/Extension:Attachments). Keeping both the README and the wiki page in sync is kind of a hassle, so I neglected the README. But yeah of course it's better if the README is also up to date. Fixed with 99c7cba9d3bf2a354298710bb4e8714838b9bc3e.
