### ISSUE TITLE
VisualEditor messes up [[Media:{{FILEPREFIX}}example.jpg]]

### ISSUE THREAD

**Issue by Gittenburg** [Gittenburg/Attachments#9]
Encountered with MediaWiki 1.35.1 and VisualEditor 0.1.2.

1. Create a page embedding an attachment with `[[Media:{{FILEPREFIX}}example.jpg]]`.
2. Edit the page with VisualEditor, edit something else and save the page.

This results in `[[Media:{{FILEPREFIX}}example.jpg]]` being replaced by an external link like `[//example.com/images/e/e5/Example%28example.jpg Media:Example - example.jpg]`.

**Comment by andrewdbate** [comment]
Sorry but I do not understand the steps to reproduce this. I have not used the `FILEPREFIX` feature before.

Is `example.jpg` a file that has already been uploaded?
Am I supposed to put `[[Media:{{FILEPREFIX}}example.jpg]]` in the source text of the article?

**Comment by Gittenburg** [comment]
Yes to both questions. The `{{FILEPREFIX}}` template essentially allows you to link an attachment relative to the current page (so attached to the current page).

I just discovered that the wiki where I encountered this bug uses a very old Parsoid version (0.8.0), so this is hopefully already fixed in the latest Parsoid.

**Comment by andrewdbate** [comment]
I have now reproduced the issue on MediaWiki 1.35.1. The step that I was missing that the file had to be an attachment to the current article.

Here were the steps I took:

1. I have an article called Test.
2. I add an attachment to Test in the usual way. The attachment is called MyAttachment.jpeg.
3. I then edit the source the source of the page and add `[[Media:{{FILEPREFIX}}MyAttachment.jpeg]]` somewhere on the page (not using the VisualEditor).
4. I save the page and which takes me back to the Read tab. The link that I just inserted is an internal wiki link to `https://wiki.mydomain.com/wiki/File:Test_-_MyAttachment.jpeg`. It appears that `FILEPREFIX` is just a macro that expands to the correct page name.
5. However, if I now go to the VisualEditor and make an edit anywhere on the page (e.g., insert a line of text, not even touching the link), the `[[Media:{{FILEPREFIX}}MyAttachment.jpeg]]` link gets messed up when I save the page. It gets turned into an external link. The link still works, but it shows up as an external link.

If I were to follow the same steps but use `File` instead of `Media` then it works as expected.

**Comment by andrewdbate** [comment]
I think I the reason why I got confused was because the documentation at https://www.mediawiki.org/wiki/Extension:Attachments says that you also have the syntax "`{{FILEPREFIX:..}}` for the parent page". I had understand that it could be any attachment (but it seems that it has to be an attachment on the current page).

How is `{{FILEPREFIX:..}}` different to `[[File:{{FILEPREFIX}}...]]`? Or when can it be used instead?

**Comment by Gittenburg** [comment]
Good question, I realize that the documentation could be better. Let me try to explain.

Let's say we have `Somepage`, `Somepage/Subpage` and `Example.png` is attached to `Somepage`. Then the image can be embedded:
* from `Somepage` with `[[File:{{FILEPREFIX}}Example.png]]`
* from `Somepage/Subpage` with `[[File:{{FILEPREFIX:..}}Example.png]]` ... which is meant to be analogous to the relative path `../Example.png`

Of course it would be better if you could just do `[[File:../Example.png]]` but afaik MediaWiki doesn't offer an API to customize file links like that.

**Comment by andrewdbate** [comment]
Ah, that makes sense. If you had a subpage of a subpage such as `Somepage/Subpage/Subpage` would you be able to write `[[File:{{FILEPREFIX:../..}}Example.png]]`? Or is that not supported?

**Comment by Gittenburg** [comment]
Yes that should also work.

**Comment by andrewdbate** [comment]
It might be worthwhile adding your example to the documentation at https://www.mediawiki.org/wiki/Extension:Attachments.

**Comment by Gittenburg** [comment]
Good idea. I added [a section explaining it](https://www.mediawiki.org/wiki/Extension:Attachments#Relatively_linking_an_attached_file).

**Comment by Gittenburg** [comment]
As it turns out this is a VisualEditor bug. [I reported it upstream](https://phabricator.wikimedia.org/T282841). Closing this here since it's not actionable for me.
